/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.testng.annotations.BeforeTest;

import static org.junit.Assert.*;

import org.junit.Before;

public class LibraryTest {
	
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        int[] arr=new int[] {2,3,4,5};
		
		assertEquals("Found",2,classUnderTest.search(arr, 4, 4));
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
